// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#ifndef _SQUARELINE_FINAL_PROJECT_UI_H
#define _SQUARELINE_FINAL_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Welcome_screen
void ui_Welcome_screen_screen_init(void);
extern lv_obj_t * ui_Welcome_screen;
void ui_event_Function_generator_button(lv_event_t * e);
extern lv_obj_t * ui_Function_generator_button;
extern lv_obj_t * ui_Function_generator_label;
void ui_event_Osciloscope_button(lv_event_t * e);
extern lv_obj_t * ui_Osciloscope_button;
extern lv_obj_t * ui_Oscilocope_label;
void ui_event_More_options_button(lv_event_t * e);
extern lv_obj_t * ui_More_options_button;
extern lv_obj_t * ui_Split_screen_label;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TemperatureLabel1;
extern lv_obj_t * ui_HumidityLabel1;
// SCREEN: ui_More_options_screen
void ui_More_options_screen_screen_init(void);
extern lv_obj_t * ui_More_options_screen;
extern lv_obj_t * ui_TemperatureLabel4;
extern lv_obj_t * ui_HumidityLabel4;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label15;
void ui_event_Look_at_screenshot_button(lv_event_t * e);
extern lv_obj_t * ui_Look_at_screenshot_button;
extern lv_obj_t * ui_See_last_screenshot_label;
void ui_event_Temp_and_humidity_button(lv_event_t * e);
extern lv_obj_t * ui_Temp_and_humidity_button;
extern lv_obj_t * ui_Temp_humidity_label;
// SCREEN: ui_Function_generator_choice1_screen
void ui_Function_generator_choice1_screen_screen_init(void);
extern lv_obj_t * ui_Function_generator_choice1_screen;
void ui_event_Sinus_button(lv_event_t * e);
extern lv_obj_t * ui_Sinus_button;
extern lv_obj_t * ui_Label11;
void ui_event_Squarewave_button(lv_event_t * e);
extern lv_obj_t * ui_Squarewave_button;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label8;
void ui_event_Sawtooth_button(lv_event_t * e);
extern lv_obj_t * ui_Sawtooth_button;
extern lv_obj_t * ui_Label9;
void ui_event_Triangle_button(lv_event_t * e);
extern lv_obj_t * ui_Triangle_button;
extern lv_obj_t * ui_Label10;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label13;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label16;
// SCREEN: ui_Preset_load
void ui_Preset_load_screen_init(void);
extern lv_obj_t * ui_Preset_load;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label23;
void ui_event_Preset_button_1(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_1;
extern lv_obj_t * ui_Labeldc1;
extern lv_obj_t * ui_Labelf1;
extern lv_obj_t * ui_Labela1;
extern lv_obj_t * ui_Labelwf1;
extern lv_obj_t * ui_Label28;
void ui_event_Preset_button_2(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_2;
extern lv_obj_t * ui_Labeldc3;
extern lv_obj_t * ui_Labelf3;
extern lv_obj_t * ui_Labela3;
extern lv_obj_t * ui_Labelwf3;
void ui_event_Preset_button_3(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_3;
extern lv_obj_t * ui_Labeldc4;
extern lv_obj_t * ui_Labelf4;
extern lv_obj_t * ui_Labela4;
extern lv_obj_t * ui_Labelwf4;
void ui_event_Preset_button_4(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_4;
extern lv_obj_t * ui_Labeldc5;
extern lv_obj_t * ui_Labelf5;
extern lv_obj_t * ui_Labela5;
extern lv_obj_t * ui_Labelwf5;
// SCREEN: ui_Function_generator_choice2_screen
void ui_Function_generator_choice2_screen_screen_init(void);
void ui_event_Function_generator_choice2_screen(lv_event_t * e);
extern lv_obj_t * ui_Function_generator_choice2_screen;
void ui_event_Slider_frequency(lv_event_t * e);
extern lv_obj_t * ui_Slider_frequency;
void ui_event_Slider_amplitude(lv_event_t * e);
extern lv_obj_t * ui_Slider_amplitude;
void ui_event_Slider_duty_cycle(lv_event_t * e);
extern lv_obj_t * ui_Slider_duty_cycle;
extern lv_obj_t * ui_Frequency_bar_label;
extern lv_obj_t * ui_Amplitude_bar_label;
extern lv_obj_t * ui_Duty_cycle_bar_label;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
void ui_event_Generate_button(lv_event_t * e);
extern lv_obj_t * ui_Generate_button;
extern lv_obj_t * ui_Label20;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Function_generator_display
void ui_Function_generator_display_screen_init(void);
void ui_event_Function_generator_display(lv_event_t * e);
extern lv_obj_t * ui_Function_generator_display;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_TemperatureLabel2;
extern lv_obj_t * ui_HumidityLabel2;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label21;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label24;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
// SCREEN: ui_Oscilloscope_display
void ui_Oscilloscope_display_screen_init(void);
extern lv_obj_t * ui_Oscilloscope_display;
extern lv_obj_t * ui_OscilloscopeChart;
extern lv_obj_t * ui_TemperatureLabel3;
extern lv_obj_t * ui_HumidityLabel3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label14;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
void ui_event_CH1minus_button(lv_event_t * e);
extern lv_obj_t * ui_CH1minus_button;
extern lv_obj_t * ui_Label47;
void ui_event_CH1plus_button(lv_event_t * e);
extern lv_obj_t * ui_CH1plus_button;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_CH1msdiv_label;
extern lv_obj_t * ui_CH2msdiv_label;
void ui_event_CH2minus_button(lv_event_t * e);
extern lv_obj_t * ui_CH2minus_button;
extern lv_obj_t * ui_Label46;
void ui_event_CH2plus_button(lv_event_t * e);
extern lv_obj_t * ui_CH2plus_button;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Ch1Vpp;
extern lv_obj_t * ui_Ch2Vpp;
// SCREEN: ui_Preset_save
void ui_Preset_save_screen_init(void);
extern lv_obj_t * ui_Preset_save;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label27;
void ui_event_Preset_button_6(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_6;
extern lv_obj_t * ui_Labeldc6;
extern lv_obj_t * ui_Labelf6;
extern lv_obj_t * ui_Labela6;
extern lv_obj_t * ui_Labelwf6;
void ui_event_Preset_button_7(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_7;
extern lv_obj_t * ui_Labeldc7;
extern lv_obj_t * ui_Labelf7;
extern lv_obj_t * ui_Labela7;
extern lv_obj_t * ui_Labelwf7;
void ui_event_Preset_button_8(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_8;
extern lv_obj_t * ui_Labeldc8;
extern lv_obj_t * ui_Labelf8;
extern lv_obj_t * ui_Labela8;
extern lv_obj_t * ui_Labelwf8;
void ui_event_Preset_button_9(lv_event_t * e);
extern lv_obj_t * ui_Preset_button_9;
extern lv_obj_t * ui_Labeldc9;
extern lv_obj_t * ui_Labelf9;
extern lv_obj_t * ui_Labela9;
extern lv_obj_t * ui_Labelwf9;
extern lv_obj_t * ui_Label29;
// SCREEN: ui_Overheat_screen
void ui_Overheat_screen_screen_init(void);
extern lv_obj_t * ui_Overheat_screen;
extern lv_obj_t * ui_Overheat_fire_picture;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screenshot_screen
void ui_Screenshot_screen_screen_init(void);
void ui_event_Screenshot_screen(lv_event_t * e);
extern lv_obj_t * ui_Screenshot_screen;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Label30(lv_event_t * e);
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_OscilloscopeChart2;
// SCREEN: ui_Temp_and_humididty_history_screen
void ui_Temp_and_humididty_history_screen_screen_init(void);
void ui_event_Temp_and_humididty_history_screen(lv_event_t * e);
extern lv_obj_t * ui_Temp_and_humididty_history_screen;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Temperature_chart;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Humidity_chart;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_450846187);    // assets/fire-5618(2).png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
