// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

//--------------------------------- INCLUDES ----------------------------------
#include "ui.h"
#include "waveform_generator.h"
#include "ui_app.h"
#include <math.h>
#include "oscilloscope.h"
#include "esp_log.h"
#include "user_interface.h"

//---------------------------------- MACROS -----------------------------------
#define OUTPUT_POINT_NUM (200U)

//-------------------------------- DATA TYPES ---------------------------------
typedef struct {
    waveform_t    waveform;
    uint32_t      frequency;
    uint32_t      amplitude_mv;
    uint32_t      duty_cycle_percentage;
} waveform_generator_t;

//---------------------- PRIVATE FUNCTION PROTOTYPES --------------------------
void _erase_screen();

void _display_wavewform_switch(lv_obj_t *ui_Label, waveform_generator_t waveform_preset);

//------------------------- STATIC DATA & CONSTANTS ---------------------------
static waveform_generator_t local_waveform_generator_state = {.waveform = WAVEFORM_SINE, .frequency = 3000, .amplitude_mv = 2500, .duty_cycle_percentage = 50};

/* Default presets. */
static waveform_generator_t waveform_preset_1 = {.waveform = WAVEFORM_SINE, .frequency = 1000, .amplitude_mv = 3000, .duty_cycle_percentage = 50};
static waveform_generator_t waveform_preset_2 = {.waveform = WAVEFORM_SQUARE, .frequency = 2000, .amplitude_mv = 1000, .duty_cycle_percentage = 40};
static waveform_generator_t waveform_preset_3 = {.waveform = WAVEFORM_TRIANGLE, .frequency = 5000, .amplitude_mv = 1500, .duty_cycle_percentage = 50};
static waveform_generator_t waveform_preset_4 = {.waveform = WAVEFORM_SAWTOOTH, .frequency = 5000, .amplitude_mv = 1500, .duty_cycle_percentage = 50};

//------------------------------- GLOBAL DATA ---------------------------------
lv_chart_series_t * ui_Chart1_series_1;

//------------------------------ PUBLIC FUNCTIONS -----------------------------

void setWaveformSine(lv_event_t * e)
{
	waveform_generator_set_waveform(DAC_CHANNEL_TO_USE, WAVEFORM_SINE);
	local_waveform_generator_state.waveform = WAVEFORM_SINE;
}

void setWaveformSawtooth(lv_event_t * e)
{
	waveform_generator_set_waveform(DAC_CHANNEL_TO_USE, WAVEFORM_SAWTOOTH);
	local_waveform_generator_state.waveform = WAVEFORM_SAWTOOTH;
}

void setWaveformTriangle(lv_event_t * e)
{
	waveform_generator_set_waveform(DAC_CHANNEL_TO_USE, WAVEFORM_TRIANGLE);
	local_waveform_generator_state.waveform = WAVEFORM_TRIANGLE;
}

void setWaveformSquarewave(lv_event_t * e)
{
	waveform_generator_set_waveform(DAC_CHANNEL_TO_USE, WAVEFORM_SQUARE);
	local_waveform_generator_state.waveform = WAVEFORM_SQUARE;
}

void startGenerating(lv_event_t * e)
{
	waveform_generator_set_waveform(DAC_CHANNEL_TO_USE, local_waveform_generator_state.waveform);
	waveform_generator_set_frequency(DAC_CHANNEL_TO_USE, (uint32_t)lv_slider_get_value(ui_Slider_frequency));
	waveform_generator_set_amplitude_mv(DAC_CHANNEL_TO_USE, (uint32_t)lv_slider_get_value(ui_Slider_amplitude));
	waveform_generator_set_duty_cycle_percenatge(DAC_CHANNEL_TO_USE, (uint32_t)lv_slider_get_value(ui_Slider_duty_cycle));

	local_waveform_generator_state.frequency = (uint32_t)lv_slider_get_value(ui_Slider_frequency);
	local_waveform_generator_state.amplitude_mv = (uint32_t)lv_slider_get_value(ui_Slider_amplitude);
	local_waveform_generator_state.duty_cycle_percentage = (uint32_t)lv_slider_get_value(ui_Slider_duty_cycle);

	xEventGroupSetBits(event_gruop_handle[DAC_CHANNEL_TO_USE], BIT_START);
}

void pauseWavegen(lv_event_t * e)
{
	xEventGroupSetBits(event_gruop_handle[DAC_CHANNEL_TO_USE], BIT_STOP);
	_erase_screen();
}

void restartWavegen(lv_event_t * e)
{
	xEventGroupSetBits(event_gruop_handle[DAC_CHANNEL_TO_USE], BIT_START);
	drawWaveform(e);
}

void drawWaveform(lv_event_t * e)
{
	ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x20F080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
	static lv_coord_t ui_Chart1_series_1_array[200] = {};

	uint32_t square_duration = (uint32_t)(OUTPUT_POINT_NUM * ((float)local_waveform_generator_state.duty_cycle_percentage / 100.0f));

	for(uint8_t i = 0; i < OUTPUT_POINT_NUM; i++)
	{
		switch(local_waveform_generator_state.waveform)
		{
			case WAVEFORM_SINE:
				ui_Chart1_series_1_array[i] = (int)(local_waveform_generator_state.amplitude_mv * (sin(i *  CONST_PERIOD_2_PI / OUTPUT_POINT_NUM) + 1) / 2);
				break;
			case WAVEFORM_TRIANGLE:
				ui_Chart1_series_1_array[i] = ((OUTPUT_POINT_NUM / 2)< i) ? (2 * local_waveform_generator_state.amplitude_mv *(OUTPUT_POINT_NUM - i) / OUTPUT_POINT_NUM) :
																			2 * local_waveform_generator_state.amplitude_mv * i / OUTPUT_POINT_NUM;
				break;
			case WAVEFORM_SAWTOOTH:
				ui_Chart1_series_1_array[i] = (OUTPUT_POINT_NUM == i) ? 0 : (i * local_waveform_generator_state.amplitude_mv / OUTPUT_POINT_NUM);
				break;
			case WAVEFORM_SQUARE:
				ui_Chart1_series_1_array[i] = (i < square_duration) ? local_waveform_generator_state.amplitude_mv : 0;
				break;
			default: break;
		}
	}
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

	lv_label_set_text_fmt(ui_Label25, "%d us", (int)(1000000.0f / 2 / local_waveform_generator_state.frequency));
	lv_label_set_text_fmt(ui_Label26, "%d us", (int)(1000000.0f / local_waveform_generator_state.frequency));
}

void _erase_screen()
{
	lv_chart_hide_series(ui_Chart1, ui_Chart1_series_1, true);
}

void _display_wavewform_switch(lv_obj_t *ui_Label, waveform_generator_t waveform_preset)
{
	switch(waveform_preset.waveform)
	{
		case WAVEFORM_SINE:
			lv_label_set_text(ui_Label, "Waveform: Sine");
			break;
		case WAVEFORM_TRIANGLE:
			lv_label_set_text(ui_Label, "Waveform: Triangle");
			break;
		case WAVEFORM_SAWTOOTH:
			lv_label_set_text(ui_Label, "Waveform: Sawtooth");
			break;
		case WAVEFORM_SQUARE:
			lv_label_set_text(ui_Label, "Waveform: Square");
			break;
		default: break;
	}
}

void lv_start_oscilloscope(lv_event_t * e)
{
	oscilloscope_start();
}

void lv_stop_oscilloscope(lv_event_t * e)
{
	oscilloscope_stop();
}

void displayPresets1(lv_event_t * e)
{
	_display_wavewform_switch(ui_Labelwf1, waveform_preset_1);
	lv_label_set_text_fmt(ui_Labelf1, "Frequency: %d Hz", (int)waveform_preset_1.frequency);
	lv_label_set_text_fmt(ui_Labela1, "Amplitude: %d mV", (int)waveform_preset_1.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc1, "Duty cycle: %d %%", (int)waveform_preset_1.duty_cycle_percentage);

	_display_wavewform_switch(ui_Labelwf3, waveform_preset_2);
	lv_label_set_text_fmt(ui_Labelf3, "Frequency: %d Hz", (int)waveform_preset_2.frequency);
	lv_label_set_text_fmt(ui_Labela3, "Amplitude: %d mV", (int)waveform_preset_2.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc3, "Duty cycle: %d %%", (int)waveform_preset_2.duty_cycle_percentage);

	_display_wavewform_switch(ui_Labelwf4, waveform_preset_3);
	lv_label_set_text_fmt(ui_Labelf4, "Frequency: %d Hz", (int)waveform_preset_3.frequency);
	lv_label_set_text_fmt(ui_Labela4, "Amplitude: %d mV", (int)waveform_preset_3.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc4, "Duty cycle: %d %%", (int)waveform_preset_3.duty_cycle_percentage);

	_display_wavewform_switch(ui_Labelwf5, waveform_preset_4);
	lv_label_set_text_fmt(ui_Labelf5, "Frequency: %d Hz", (int)waveform_preset_4.frequency);
	lv_label_set_text_fmt(ui_Labela5, "Amplitude: %d mV", (int)waveform_preset_4.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc5, "Duty cycle: %d %%", (int)waveform_preset_4.duty_cycle_percentage);
}

void DisplayPresets2(lv_event_t * e)
{
	_display_wavewform_switch(ui_Labelwf6, waveform_preset_1);
	lv_label_set_text_fmt(ui_Labelf6, "Frequency: %d Hz", (int)waveform_preset_1.frequency);
	lv_label_set_text_fmt(ui_Labela6, "Amplitude: %d mV", (int)waveform_preset_1.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc6, "Duty cycle: %d %%", (int)waveform_preset_1.duty_cycle_percentage);

	_display_wavewform_switch(ui_Labelwf7, waveform_preset_2);
	lv_label_set_text_fmt(ui_Labelf7, "Frequency: %d Hz", (int)waveform_preset_2.frequency);
	lv_label_set_text_fmt(ui_Labela7, "Amplitude: %d mV", (int)waveform_preset_2.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc7, "Duty cycle: %d %%", (int)waveform_preset_2.duty_cycle_percentage);

	_display_wavewform_switch(ui_Labelwf8, waveform_preset_3);
	lv_label_set_text_fmt(ui_Labelf8, "Frequency: %d Hz", (int)waveform_preset_3.frequency);
	lv_label_set_text_fmt(ui_Labela8, "Amplitude: %d mV", (int)waveform_preset_3.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc8, "Duty cycle: %d %%", (int)waveform_preset_3.duty_cycle_percentage);

	_display_wavewform_switch(ui_Labelwf9, waveform_preset_4);
	lv_label_set_text_fmt(ui_Labelf9, "Frequency: %d Hz", (int)waveform_preset_4.frequency);
	lv_label_set_text_fmt(ui_Labela9, "Amplitude: %d mV", (int)waveform_preset_4.amplitude_mv);
	lv_label_set_text_fmt(ui_Labeldc9, "Duty cycle: %d %%", (int)waveform_preset_4.duty_cycle_percentage);
}

void loadPreset1(lv_event_t * e)
{
	local_waveform_generator_state = waveform_preset_1;
}

void loadPreset2(lv_event_t * e)
{
	local_waveform_generator_state = waveform_preset_2;
}

void loadPreset3(lv_event_t * e)
{
	local_waveform_generator_state = waveform_preset_3;
}

void loadPreset4(lv_event_t * e)
{
	local_waveform_generator_state = waveform_preset_4;
}

void savePreset1(lv_event_t * e)
{
	waveform_preset_1 = local_waveform_generator_state;
}

void savePreset2(lv_event_t * e)
{
	waveform_preset_2 = local_waveform_generator_state;
}

void savePreset3(lv_event_t * e)
{
	waveform_preset_3 = local_waveform_generator_state;
}

void savePreset4(lv_event_t * e)
{
	waveform_preset_4 = local_waveform_generator_state;
}

void setSliders(lv_event_t * e)
{
	lv_slider_set_value(ui_Slider_frequency, local_waveform_generator_state.frequency, LV_ANIM_OFF);
	lv_label_set_text_fmt(ui_Frequency_bar_label, "%d Hz", (int)local_waveform_generator_state.frequency);
	lv_slider_set_value(ui_Slider_amplitude, local_waveform_generator_state.amplitude_mv, LV_ANIM_OFF);
	lv_label_set_text_fmt(ui_Amplitude_bar_label, "%d mV", (int)local_waveform_generator_state.amplitude_mv);
	lv_slider_set_value(ui_Slider_duty_cycle, local_waveform_generator_state.duty_cycle_percentage, LV_ANIM_OFF);
	lv_label_set_text_fmt(ui_Duty_cycle_bar_label, "%d %%", (int)local_waveform_generator_state.duty_cycle_percentage);
}

void takeScreenshot(lv_event_t * e)
{
	oscilloscope_screenshot();
}

void drawScreenshot(lv_event_t * e)
{
	oscilloscope_display_screenshot();
}

void showTempAndHumidityHistory(lv_event_t * e)
{
	user_interface_send_event(EVENT_SHOW_TEMP_HISTORY, 0);
}

void CH1ZoomOut(lv_event_t * e)
{
	oscilloscopeCH1_zoom(OSCILLOSCOPE_ZOOM_OUT);
}

void CH1ZoomIn(lv_event_t * e)
{
	oscilloscopeCH1_zoom(OSCILLOSCOPE_ZOOM_IN);
}

void CH2ZoomOut(lv_event_t * e)
{
	oscilloscopeCH2_zoom(OSCILLOSCOPE_ZOOM_OUT);
}

void CH2ZoomIn(lv_event_t * e)
{
	oscilloscopeCH2_zoom(OSCILLOSCOPE_ZOOM_IN);
}
