// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lv_start_oscilloscope(lv_event_t * e);
void setWaveformSine(lv_event_t * e);
void setWaveformSquarewave(lv_event_t * e);
void setWaveformSawtooth(lv_event_t * e);
void setWaveformTriangle(lv_event_t * e);
void displayPresets1(lv_event_t * e);
void loadPreset1(lv_event_t * e);
void loadPreset2(lv_event_t * e);
void loadPreset3(lv_event_t * e);
void loadPreset4(lv_event_t * e);
void setSliders(lv_event_t * e);
void startGenerating(lv_event_t * e);
void drawWaveform(lv_event_t * e);
void pauseWavegen(lv_event_t * e);
void restartWavegen(lv_event_t * e);
void DisplayPresets2(lv_event_t * e);
void lv_stop_oscilloscope(lv_event_t * e);
void takeScreenshot(lv_event_t * e);
void CH1ZoomOut(lv_event_t * e);
void CH1ZoomIn(lv_event_t * e);
void CH2ZoomOut(lv_event_t * e);
void CH2ZoomIn(lv_event_t * e);
void savePreset1(lv_event_t * e);
void savePreset2(lv_event_t * e);
void savePreset3(lv_event_t * e);
void savePreset4(lv_event_t * e);
void drawScreenshot(lv_event_t * e);
void showTempAndHumidityHistory(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
