// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Function_generator_choice2_screen_screen_init(void)
{
    ui_Function_generator_choice2_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Function_generator_choice2_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider_frequency = lv_slider_create(ui_Function_generator_choice2_screen);
    lv_slider_set_range(ui_Slider_frequency, 1000, 10000);
    lv_slider_set_value(ui_Slider_frequency, 3000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_frequency) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_frequency, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_frequency, 180);
    lv_obj_set_height(ui_Slider_frequency, 10);
    lv_obj_set_x(ui_Slider_frequency, 0);
    lv_obj_set_y(ui_Slider_frequency, -75);
    lv_obj_set_align(ui_Slider_frequency, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider_frequency, lv_color_hex(0x20F080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_frequency, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider_frequency, lv_color_hex(0x20F080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider_frequency, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider_frequency, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_frequency, lv_color_hex(0x20F080), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_frequency, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider_amplitude = lv_slider_create(ui_Function_generator_choice2_screen);
    lv_slider_set_range(ui_Slider_amplitude, 100, 3300);
    lv_slider_set_value(ui_Slider_amplitude, 2500, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_amplitude) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_amplitude, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_amplitude, 180);
    lv_obj_set_height(ui_Slider_amplitude, 10);
    lv_obj_set_x(ui_Slider_amplitude, 0);
    lv_obj_set_y(ui_Slider_amplitude, -30);
    lv_obj_set_align(ui_Slider_amplitude, LV_ALIGN_CENTER);

    lv_obj_set_style_radius(ui_Slider_amplitude, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider_amplitude, lv_color_hex(0x20F080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_amplitude, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_amplitude, lv_color_hex(0x20F080), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_amplitude, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider_duty_cycle = lv_slider_create(ui_Function_generator_choice2_screen);
    lv_slider_set_value(ui_Slider_duty_cycle, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_duty_cycle) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_duty_cycle, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_duty_cycle, 180);
    lv_obj_set_height(ui_Slider_duty_cycle, 10);
    lv_obj_set_x(ui_Slider_duty_cycle, 0);
    lv_obj_set_y(ui_Slider_duty_cycle, 15);
    lv_obj_set_align(ui_Slider_duty_cycle, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider_duty_cycle, lv_color_hex(0x20F080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_duty_cycle, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_duty_cycle, lv_color_hex(0x20F080), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_duty_cycle, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Frequency_bar_label = lv_label_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Frequency_bar_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Frequency_bar_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Frequency_bar_label, 40);
    lv_obj_set_y(ui_Frequency_bar_label, -97);
    lv_obj_set_align(ui_Frequency_bar_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Frequency_bar_label, "3000 Hz");
    lv_obj_set_style_text_color(ui_Frequency_bar_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Frequency_bar_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Amplitude_bar_label = lv_label_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Amplitude_bar_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amplitude_bar_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Amplitude_bar_label, 42);
    lv_obj_set_y(ui_Amplitude_bar_label, -52);
    lv_obj_set_align(ui_Amplitude_bar_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Amplitude_bar_label, "2500 mV");

    ui_Duty_cycle_bar_label = lv_label_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Duty_cycle_bar_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Duty_cycle_bar_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Duty_cycle_bar_label, 34);
    lv_obj_set_y(ui_Duty_cycle_bar_label, -7);
    lv_obj_set_align(ui_Duty_cycle_bar_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Duty_cycle_bar_label, "50 %");

    ui_Label17 = lv_label_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -32);
    lv_obj_set_y(ui_Label17, -97);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Frequency: ");

    ui_Label18 = lv_label_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -32);
    lv_obj_set_y(ui_Label18, -52);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Amplitude: ");

    ui_Label19 = lv_label_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -29);
    lv_obj_set_y(ui_Label19, -7);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Duty cycle: ");

    ui_Generate_button = lv_btn_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Generate_button, 160);
    lv_obj_set_height(ui_Generate_button, 50);
    lv_obj_set_x(ui_Generate_button, 0);
    lv_obj_set_y(ui_Generate_button, 67);
    lv_obj_set_align(ui_Generate_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Generate_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Generate_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Generate_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Generate_button, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Generate_button, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Generate_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Generate_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Generate_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label20 = lv_label_create(ui_Generate_button);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Generate");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Function_generator_choice2_screen);
    lv_obj_set_width(ui_Button3, 52);
    lv_obj_set_height(ui_Button3, 25);
    lv_obj_set_x(ui_Button3, -126);
    lv_obj_set_y(ui_Button3, 99);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button3, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label4 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Back");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider_frequency, ui_event_Slider_frequency, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider_amplitude, ui_event_Slider_amplitude, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider_duty_cycle, ui_event_Slider_duty_cycle, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Generate_button, ui_event_Generate_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Function_generator_choice2_screen, ui_event_Function_generator_choice2_screen, LV_EVENT_ALL,
                        NULL);

}
