// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_More_options_screen_screen_init(void)
{
    ui_More_options_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_More_options_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TemperatureLabel4 = lv_label_create(ui_More_options_screen);
    lv_obj_set_width(ui_TemperatureLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel4, -80);
    lv_obj_set_y(ui_TemperatureLabel4, -110);
    lv_obj_set_align(ui_TemperatureLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel4, "Temperature: 0 °C");
    lv_obj_set_style_text_font(ui_TemperatureLabel4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel4 = lv_label_create(ui_More_options_screen);
    lv_obj_set_width(ui_HumidityLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabel4, 70);
    lv_obj_set_y(ui_HumidityLabel4, -110);
    lv_obj_set_align(ui_HumidityLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel4, "Humidity: 0%");
    lv_obj_set_style_text_font(ui_HumidityLabel4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_More_options_screen);
    lv_obj_set_width(ui_Button6, 52);
    lv_obj_set_height(ui_Button6, 25);
    lv_obj_set_x(ui_Button6, -126);
    lv_obj_set_y(ui_Button6, 99);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button6, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button6, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label15 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Back");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Look_at_screenshot_button = lv_btn_create(ui_More_options_screen);
    lv_obj_set_width(ui_Look_at_screenshot_button, 185);
    lv_obj_set_height(ui_Look_at_screenshot_button, 40);
    lv_obj_set_x(ui_Look_at_screenshot_button, 0);
    lv_obj_set_y(ui_Look_at_screenshot_button, 25);
    lv_obj_set_align(ui_Look_at_screenshot_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Look_at_screenshot_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Look_at_screenshot_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Look_at_screenshot_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Look_at_screenshot_button, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Look_at_screenshot_button, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Look_at_screenshot_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Look_at_screenshot_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Look_at_screenshot_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_See_last_screenshot_label = lv_label_create(ui_Look_at_screenshot_button);
    lv_obj_set_width(ui_See_last_screenshot_label, 161);
    lv_obj_set_height(ui_See_last_screenshot_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_See_last_screenshot_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_See_last_screenshot_label, "See last screenshot");
    lv_obj_set_style_text_color(ui_See_last_screenshot_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_See_last_screenshot_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_See_last_screenshot_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp_and_humidity_button = lv_btn_create(ui_More_options_screen);
    lv_obj_set_width(ui_Temp_and_humidity_button, 185);
    lv_obj_set_height(ui_Temp_and_humidity_button, 40);
    lv_obj_set_x(ui_Temp_and_humidity_button, 0);
    lv_obj_set_y(ui_Temp_and_humidity_button, -25);
    lv_obj_set_align(ui_Temp_and_humidity_button, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Temp_and_humidity_button, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_style_bg_color(ui_Temp_and_humidity_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temp_and_humidity_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Temp_and_humidity_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Temp_and_humidity_button, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Temp_and_humidity_button, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Temp_and_humidity_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Temp_and_humidity_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Temp_and_humidity_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Temp_humidity_label = lv_label_create(ui_Temp_and_humidity_button);
    lv_obj_set_width(ui_Temp_humidity_label, 119);
    lv_obj_set_height(ui_Temp_humidity_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Temp_humidity_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp_humidity_label, "Temp&Humidity");
    lv_obj_set_style_text_color(ui_Temp_humidity_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp_humidity_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp_humidity_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Look_at_screenshot_button, ui_event_Look_at_screenshot_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp_and_humidity_button, ui_event_Temp_and_humidity_button, LV_EVENT_ALL, NULL);

}
