// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Oscilloscope_display_screen_init(void)
{
    ui_Oscilloscope_display = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Oscilloscope_display, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Oscilloscope_display, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Oscilloscope_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Oscilloscope_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Oscilloscope_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Oscilloscope_display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OscilloscopeChart = lv_chart_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_OscilloscopeChart, 220);
    lv_obj_set_height(ui_OscilloscopeChart, 130);
    lv_obj_set_x(ui_OscilloscopeChart, 5);
    lv_obj_set_y(ui_OscilloscopeChart, -17);
    lv_obj_set_align(ui_OscilloscopeChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_OscilloscopeChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_OscilloscopeChart, 200);
    lv_chart_set_range(ui_OscilloscopeChart, LV_CHART_AXIS_PRIMARY_Y, 0, 3300);
    lv_chart_set_axis_tick(ui_OscilloscopeChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 1, false, 50);
    lv_chart_set_axis_tick(ui_OscilloscopeChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 1, false, 50);
    lv_chart_set_axis_tick(ui_OscilloscopeChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 1, false, 25);



    lv_obj_set_style_line_color(ui_OscilloscopeChart, lv_color_hex(0x20F080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_OscilloscopeChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TemperatureLabel3 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_TemperatureLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel3, -80);
    lv_obj_set_y(ui_TemperatureLabel3, -110);
    lv_obj_set_align(ui_TemperatureLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel3, "Temperature: 0 °C");
    lv_obj_set_style_text_font(ui_TemperatureLabel3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel3 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_HumidityLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabel3, 70);
    lv_obj_set_y(ui_HumidityLabel3, -110);
    lv_obj_set_align(ui_HumidityLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel3, "Humidity: 0%");
    lv_obj_set_style_text_font(ui_HumidityLabel3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Button5, 52);
    lv_obj_set_height(ui_Button5, 25);
    lv_obj_set_x(ui_Button5, -130);
    lv_obj_set_y(ui_Button5, 102);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button5, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button5, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label14 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Back");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Button13, 66);
    lv_obj_set_height(ui_Button13, 27);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, -85);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button13, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label31 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Screenshot");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -131);
    lv_obj_set_y(ui_Label41, -72);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "3.3 V");
    lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -136);
    lv_obj_set_y(ui_Label42, -45);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "2.475 V");
    lv_obj_set_style_text_font(ui_Label42, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -132);
    lv_obj_set_y(ui_Label43, -18);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "1.35 V");
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -136);
    lv_obj_set_y(ui_Label44, 10);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "0.825 V");
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -127);
    lv_obj_set_y(ui_Label45, 38);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "0 V");
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH1minus_button = lv_btn_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_CH1minus_button, 38);
    lv_obj_set_height(ui_CH1minus_button, 21);
    lv_obj_set_x(ui_CH1minus_button, -66);
    lv_obj_set_y(ui_CH1minus_button, 74);
    lv_obj_set_align(ui_CH1minus_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CH1minus_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CH1minus_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CH1minus_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_CH1minus_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_CH1minus_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label47 = lv_label_create(ui_CH1minus_button);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "-");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH1plus_button = lv_btn_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_CH1plus_button, 38);
    lv_obj_set_height(ui_CH1plus_button, 21);
    lv_obj_set_x(ui_CH1plus_button, -21);
    lv_obj_set_y(ui_CH1plus_button, 74);
    lv_obj_set_align(ui_CH1plus_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CH1plus_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CH1plus_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CH1plus_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_CH1plus_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_CH1plus_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label48 = lv_label_create(ui_CH1plus_button);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "+");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH1msdiv_label = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_CH1msdiv_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CH1msdiv_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH1msdiv_label, -44);
    lv_obj_set_y(ui_CH1msdiv_label, 94);
    lv_obj_set_align(ui_CH1msdiv_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CH1msdiv_label, "1000 ms/div");
    lv_obj_set_style_text_font(ui_CH1msdiv_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH2msdiv_label = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_CH2msdiv_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CH2msdiv_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CH2msdiv_label, 65);
    lv_obj_set_y(ui_CH2msdiv_label, 94);
    lv_obj_set_align(ui_CH2msdiv_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CH2msdiv_label, "1000 ms/div");
    lv_obj_set_style_text_font(ui_CH2msdiv_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH2minus_button = lv_btn_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_CH2minus_button, 38);
    lv_obj_set_height(ui_CH2minus_button, 21);
    lv_obj_set_x(ui_CH2minus_button, 42);
    lv_obj_set_y(ui_CH2minus_button, 74);
    lv_obj_set_align(ui_CH2minus_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CH2minus_button, lv_color_hex(0xFFF800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CH2minus_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CH2minus_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_CH2minus_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_CH2minus_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label46 = lv_label_create(ui_CH2minus_button);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "-");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CH2plus_button = lv_btn_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_CH2plus_button, 38);
    lv_obj_set_height(ui_CH2plus_button, 21);
    lv_obj_set_x(ui_CH2plus_button, 87);
    lv_obj_set_y(ui_CH2plus_button, 74);
    lv_obj_set_align(ui_CH2plus_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CH2plus_button, lv_color_hex(0xFFF800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CH2plus_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CH2plus_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_CH2plus_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_CH2plus_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label49 = lv_label_create(ui_CH2plus_button);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "+");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ch1Vpp = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Ch1Vpp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch1Vpp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch1Vpp, -43);
    lv_obj_set_y(ui_Ch1Vpp, 108);
    lv_obj_set_align(ui_Ch1Vpp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch1Vpp, "CH1: 0 mVpp");
    lv_obj_set_style_text_font(ui_Ch1Vpp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ch2Vpp = lv_label_create(ui_Oscilloscope_display);
    lv_obj_set_width(ui_Ch2Vpp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch2Vpp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch2Vpp, 65);
    lv_obj_set_y(ui_Ch2Vpp, 108);
    lv_obj_set_align(ui_Ch2Vpp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch2Vpp, "CH2: 0 mVpp");
    lv_obj_set_style_text_font(ui_Ch2Vpp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CH1minus_button, ui_event_CH1minus_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CH1plus_button, ui_event_CH1plus_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CH2minus_button, ui_event_CH2minus_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CH2plus_button, ui_event_CH2plus_button, LV_EVENT_ALL, NULL);

}
