// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Overheat_screen_screen_init(void)
{
    ui_Overheat_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Overheat_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Overheat_fire_picture = lv_img_create(ui_Overheat_screen);
    lv_img_set_src(ui_Overheat_fire_picture, &ui_img_450846187);
    lv_obj_set_width(ui_Overheat_fire_picture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Overheat_fire_picture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Overheat_fire_picture, 0);
    lv_obj_set_y(ui_Overheat_fire_picture, -33);
    lv_obj_set_align(ui_Overheat_fire_picture, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Overheat_fire_picture, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Overheat_fire_picture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Overheat_fire_picture, 200);

    ui_Label5 = lv_label_create(ui_Overheat_screen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 39);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "The board has reached max temperature!");

    ui_Label6 = lv_label_create(ui_Overheat_screen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 71);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Please restart the device.");

    ui_Label7 = lv_label_create(ui_Overheat_screen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -100);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "OVERHEAT ERROR!");
    lv_label_set_recolor(ui_Label7, "true");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xBF1919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
