// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Preset_save_screen_init(void)
{
    ui_Preset_save = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Preset_save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button11 = lv_btn_create(ui_Preset_save);
    lv_obj_set_width(ui_Button11, 53);
    lv_obj_set_height(ui_Button11, 25);
    lv_obj_set_x(ui_Button11, -126);
    lv_obj_set_y(ui_Button11, 99);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button11, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button11, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label27 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Back");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_6 = lv_btn_create(ui_Preset_save);
    lv_obj_set_width(ui_Preset_button_6, 120);
    lv_obj_set_height(ui_Preset_button_6, 70);
    lv_obj_set_x(ui_Preset_button_6, -62);
    lv_obj_set_y(ui_Preset_button_6, -39);
    lv_obj_set_align(ui_Preset_button_6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_6, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_6, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_6, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_6, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc6 = lv_label_create(ui_Preset_button_6);
    lv_obj_set_width(ui_Labeldc6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc6, 0);
    lv_obj_set_y(ui_Labeldc6, 20);
    lv_obj_set_align(ui_Labeldc6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc6, "Duty cycle: 50 %");
    lv_obj_set_style_text_color(ui_Labeldc6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf6 = lv_label_create(ui_Preset_button_6);
    lv_obj_set_width(ui_Labelf6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf6, 0);
    lv_obj_set_y(ui_Labelf6, -8);
    lv_obj_set_align(ui_Labelf6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf6, "Frequency: 1000 Hz");
    lv_obj_set_style_text_color(ui_Labelf6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela6 = lv_label_create(ui_Preset_button_6);
    lv_obj_set_width(ui_Labela6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela6, 0);
    lv_obj_set_y(ui_Labela6, 6);
    lv_obj_set_align(ui_Labela6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela6, "Amplitude: 3000 mV");
    lv_obj_set_style_text_color(ui_Labela6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf6 = lv_label_create(ui_Preset_button_6);
    lv_obj_set_width(ui_Labelwf6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf6, 0);
    lv_obj_set_y(ui_Labelwf6, -22);
    lv_obj_set_align(ui_Labelwf6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf6, "Waveform: Sine");
    lv_obj_set_style_text_color(ui_Labelwf6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_7 = lv_btn_create(ui_Preset_save);
    lv_obj_set_width(ui_Preset_button_7, 120);
    lv_obj_set_height(ui_Preset_button_7, 70);
    lv_obj_set_x(ui_Preset_button_7, 67);
    lv_obj_set_y(ui_Preset_button_7, -39);
    lv_obj_set_align(ui_Preset_button_7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_7, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_7, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_7, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_7, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_7, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc7 = lv_label_create(ui_Preset_button_7);
    lv_obj_set_width(ui_Labeldc7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc7, 0);
    lv_obj_set_y(ui_Labeldc7, 20);
    lv_obj_set_align(ui_Labeldc7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc7, "Duty cycle: 40 %");
    lv_obj_set_style_text_color(ui_Labeldc7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf7 = lv_label_create(ui_Preset_button_7);
    lv_obj_set_width(ui_Labelf7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf7, 0);
    lv_obj_set_y(ui_Labelf7, -8);
    lv_obj_set_align(ui_Labelf7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf7, "Frequency: 2000 Hz");
    lv_obj_set_style_text_color(ui_Labelf7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela7 = lv_label_create(ui_Preset_button_7);
    lv_obj_set_width(ui_Labela7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela7, 0);
    lv_obj_set_y(ui_Labela7, 6);
    lv_obj_set_align(ui_Labela7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela7, "Amplitude: 1000 mV");
    lv_obj_set_style_text_color(ui_Labela7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf7 = lv_label_create(ui_Preset_button_7);
    lv_obj_set_width(ui_Labelwf7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf7, 0);
    lv_obj_set_y(ui_Labelwf7, -22);
    lv_obj_set_align(ui_Labelwf7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf7, "Waveform: Square");
    lv_obj_set_style_text_color(ui_Labelwf7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_8 = lv_btn_create(ui_Preset_save);
    lv_obj_set_width(ui_Preset_button_8, 120);
    lv_obj_set_height(ui_Preset_button_8, 70);
    lv_obj_set_x(ui_Preset_button_8, -62);
    lv_obj_set_y(ui_Preset_button_8, 40);
    lv_obj_set_align(ui_Preset_button_8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_8, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_8, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_8, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_8, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_8, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc8 = lv_label_create(ui_Preset_button_8);
    lv_obj_set_width(ui_Labeldc8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc8, 0);
    lv_obj_set_y(ui_Labeldc8, 20);
    lv_obj_set_align(ui_Labeldc8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc8, "Duty cycle: 50 %");
    lv_obj_set_style_text_color(ui_Labeldc8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf8 = lv_label_create(ui_Preset_button_8);
    lv_obj_set_width(ui_Labelf8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf8, 0);
    lv_obj_set_y(ui_Labelf8, -8);
    lv_obj_set_align(ui_Labelf8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf8, "Frequency: 5000 Hz");
    lv_obj_set_style_text_color(ui_Labelf8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela8 = lv_label_create(ui_Preset_button_8);
    lv_obj_set_width(ui_Labela8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela8, 0);
    lv_obj_set_y(ui_Labela8, 6);
    lv_obj_set_align(ui_Labela8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela8, "Amplitude: 1500 mV");
    lv_obj_set_style_text_color(ui_Labela8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf8 = lv_label_create(ui_Preset_button_8);
    lv_obj_set_width(ui_Labelwf8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf8, 0);
    lv_obj_set_y(ui_Labelwf8, -22);
    lv_obj_set_align(ui_Labelwf8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf8, "Waveform: Triangle");
    lv_obj_set_style_text_color(ui_Labelwf8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf8, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_9 = lv_btn_create(ui_Preset_save);
    lv_obj_set_width(ui_Preset_button_9, 120);
    lv_obj_set_height(ui_Preset_button_9, 70);
    lv_obj_set_x(ui_Preset_button_9, 66);
    lv_obj_set_y(ui_Preset_button_9, 39);
    lv_obj_set_align(ui_Preset_button_9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_9, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_9, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_9, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_9, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc9 = lv_label_create(ui_Preset_button_9);
    lv_obj_set_width(ui_Labeldc9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc9, 0);
    lv_obj_set_y(ui_Labeldc9, 20);
    lv_obj_set_align(ui_Labeldc9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc9, "Duty cycle: 50 %");
    lv_obj_set_style_text_color(ui_Labeldc9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf9 = lv_label_create(ui_Preset_button_9);
    lv_obj_set_width(ui_Labelf9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf9, 0);
    lv_obj_set_y(ui_Labelf9, -8);
    lv_obj_set_align(ui_Labelf9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf9, "Frequency: 5000 Hz");
    lv_obj_set_style_text_color(ui_Labelf9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela9 = lv_label_create(ui_Preset_button_9);
    lv_obj_set_width(ui_Labela9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela9, 0);
    lv_obj_set_y(ui_Labela9, 6);
    lv_obj_set_align(ui_Labela9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela9, "Amplitude: 1500 mV");
    lv_obj_set_style_text_color(ui_Labela9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf9 = lv_label_create(ui_Preset_button_9);
    lv_obj_set_width(ui_Labelwf9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf9, 0);
    lv_obj_set_y(ui_Labelwf9, -22);
    lv_obj_set_align(ui_Labelwf9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf9, "Waveform: Sawtooth");
    lv_obj_set_style_text_color(ui_Labelwf9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Preset_save);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, -96);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Choose preset to override");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_6, ui_event_Preset_button_6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_7, ui_event_Preset_button_7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_8, ui_event_Preset_button_8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_9, ui_event_Preset_button_9, LV_EVENT_ALL, NULL);

}
