// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Preset_load_screen_init(void)
{
    ui_Preset_load = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Preset_load, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button9 = lv_btn_create(ui_Preset_load);
    lv_obj_set_width(ui_Button9, 53);
    lv_obj_set_height(ui_Button9, 25);
    lv_obj_set_x(ui_Button9, -126);
    lv_obj_set_y(ui_Button9, 99);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button9, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button9, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label23 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Back");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_1 = lv_btn_create(ui_Preset_load);
    lv_obj_set_width(ui_Preset_button_1, 120);
    lv_obj_set_height(ui_Preset_button_1, 70);
    lv_obj_set_x(ui_Preset_button_1, -62);
    lv_obj_set_y(ui_Preset_button_1, -39);
    lv_obj_set_align(ui_Preset_button_1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_1, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_1, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_1, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_1, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc1 = lv_label_create(ui_Preset_button_1);
    lv_obj_set_width(ui_Labeldc1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc1, 0);
    lv_obj_set_y(ui_Labeldc1, 20);
    lv_obj_set_align(ui_Labeldc1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc1, "Duty cycle: 50 %");
    lv_obj_set_style_text_color(ui_Labeldc1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf1 = lv_label_create(ui_Preset_button_1);
    lv_obj_set_width(ui_Labelf1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf1, 0);
    lv_obj_set_y(ui_Labelf1, -8);
    lv_obj_set_align(ui_Labelf1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf1, "Frequency: 1000 Hz");
    lv_obj_set_style_text_color(ui_Labelf1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela1 = lv_label_create(ui_Preset_button_1);
    lv_obj_set_width(ui_Labela1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela1, 0);
    lv_obj_set_y(ui_Labela1, 6);
    lv_obj_set_align(ui_Labela1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela1, "Amplitude: 3000 mV");
    lv_obj_set_style_text_color(ui_Labela1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf1 = lv_label_create(ui_Preset_button_1);
    lv_obj_set_width(ui_Labelwf1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf1, 0);
    lv_obj_set_y(ui_Labelwf1, -22);
    lv_obj_set_align(ui_Labelwf1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf1, "Waveform: Sine");
    lv_obj_set_style_text_color(ui_Labelwf1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Preset_load);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, -96);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Choose preset waveform");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_2 = lv_btn_create(ui_Preset_load);
    lv_obj_set_width(ui_Preset_button_2, 120);
    lv_obj_set_height(ui_Preset_button_2, 70);
    lv_obj_set_x(ui_Preset_button_2, 67);
    lv_obj_set_y(ui_Preset_button_2, -39);
    lv_obj_set_align(ui_Preset_button_2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_2, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_2, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_2, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_2, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc3 = lv_label_create(ui_Preset_button_2);
    lv_obj_set_width(ui_Labeldc3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc3, 0);
    lv_obj_set_y(ui_Labeldc3, 20);
    lv_obj_set_align(ui_Labeldc3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc3, "Duty cycle: 40 %");
    lv_obj_set_style_text_color(ui_Labeldc3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf3 = lv_label_create(ui_Preset_button_2);
    lv_obj_set_width(ui_Labelf3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf3, 0);
    lv_obj_set_y(ui_Labelf3, -8);
    lv_obj_set_align(ui_Labelf3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf3, "Frequency: 2000 Hz");
    lv_obj_set_style_text_color(ui_Labelf3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela3 = lv_label_create(ui_Preset_button_2);
    lv_obj_set_width(ui_Labela3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela3, 0);
    lv_obj_set_y(ui_Labela3, 6);
    lv_obj_set_align(ui_Labela3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela3, "Amplitude: 1000 mV");
    lv_obj_set_style_text_color(ui_Labela3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf3 = lv_label_create(ui_Preset_button_2);
    lv_obj_set_width(ui_Labelwf3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf3, 0);
    lv_obj_set_y(ui_Labelwf3, -22);
    lv_obj_set_align(ui_Labelwf3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf3, "Waveform: Square");
    lv_obj_set_style_text_color(ui_Labelwf3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_3 = lv_btn_create(ui_Preset_load);
    lv_obj_set_width(ui_Preset_button_3, 120);
    lv_obj_set_height(ui_Preset_button_3, 70);
    lv_obj_set_x(ui_Preset_button_3, -62);
    lv_obj_set_y(ui_Preset_button_3, 40);
    lv_obj_set_align(ui_Preset_button_3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_3, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_3, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_3, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_3, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc4 = lv_label_create(ui_Preset_button_3);
    lv_obj_set_width(ui_Labeldc4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc4, 0);
    lv_obj_set_y(ui_Labeldc4, 20);
    lv_obj_set_align(ui_Labeldc4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc4, "Duty cycle: 50 %");
    lv_obj_set_style_text_color(ui_Labeldc4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf4 = lv_label_create(ui_Preset_button_3);
    lv_obj_set_width(ui_Labelf4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf4, 0);
    lv_obj_set_y(ui_Labelf4, -8);
    lv_obj_set_align(ui_Labelf4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf4, "Frequency: 5000 Hz");
    lv_obj_set_style_text_color(ui_Labelf4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela4 = lv_label_create(ui_Preset_button_3);
    lv_obj_set_width(ui_Labela4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela4, 0);
    lv_obj_set_y(ui_Labela4, 6);
    lv_obj_set_align(ui_Labela4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela4, "Amplitude: 1500 mV");
    lv_obj_set_style_text_color(ui_Labela4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf4 = lv_label_create(ui_Preset_button_3);
    lv_obj_set_width(ui_Labelwf4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf4, 0);
    lv_obj_set_y(ui_Labelwf4, -22);
    lv_obj_set_align(ui_Labelwf4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf4, "Waveform: Triangle");
    lv_obj_set_style_text_color(ui_Labelwf4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset_button_4 = lv_btn_create(ui_Preset_load);
    lv_obj_set_width(ui_Preset_button_4, 120);
    lv_obj_set_height(ui_Preset_button_4, 70);
    lv_obj_set_x(ui_Preset_button_4, 66);
    lv_obj_set_y(ui_Preset_button_4, 39);
    lv_obj_set_align(ui_Preset_button_4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Preset_button_4, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Preset_button_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Preset_button_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Preset_button_4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Preset_button_4, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Preset_button_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Preset_button_4, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Preset_button_4, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Labeldc5 = lv_label_create(ui_Preset_button_4);
    lv_obj_set_width(ui_Labeldc5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldc5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldc5, 0);
    lv_obj_set_y(ui_Labeldc5, 20);
    lv_obj_set_align(ui_Labeldc5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldc5, "Duty cycle: 50 %");
    lv_obj_set_style_text_color(ui_Labeldc5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldc5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldc5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelf5 = lv_label_create(ui_Preset_button_4);
    lv_obj_set_width(ui_Labelf5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelf5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelf5, 0);
    lv_obj_set_y(ui_Labelf5, -8);
    lv_obj_set_align(ui_Labelf5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelf5, "Frequency: 5000 Hz");
    lv_obj_set_style_text_color(ui_Labelf5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelf5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelf5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labela5 = lv_label_create(ui_Preset_button_4);
    lv_obj_set_width(ui_Labela5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labela5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labela5, 0);
    lv_obj_set_y(ui_Labela5, 6);
    lv_obj_set_align(ui_Labela5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labela5, "Amplitude: 1500 mV");
    lv_obj_set_style_text_color(ui_Labela5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labela5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labela5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelwf5 = lv_label_create(ui_Preset_button_4);
    lv_obj_set_width(ui_Labelwf5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelwf5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelwf5, 0);
    lv_obj_set_y(ui_Labelwf5, -22);
    lv_obj_set_align(ui_Labelwf5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelwf5, "Waveform: Sawtooth");
    lv_obj_set_style_text_color(ui_Labelwf5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelwf5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelwf5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_1, ui_event_Preset_button_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_2, ui_event_Preset_button_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_3, ui_event_Preset_button_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Preset_button_4, ui_event_Preset_button_4, LV_EVENT_ALL, NULL);

}
