// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Screenshot_screen_screen_init(void)
{
    ui_Screenshot_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenshot_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_btn_create(ui_Screenshot_screen);
    lv_obj_set_width(ui_Button12, 90);
    lv_obj_set_height(ui_Button12, 29);
    lv_obj_set_x(ui_Button12, 0);
    lv_obj_set_y(ui_Button12, 84);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button12, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button12, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label30 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Very nice");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OscilloscopeChart2 = lv_chart_create(ui_Screenshot_screen);
    lv_obj_set_width(ui_OscilloscopeChart2, 220);
    lv_obj_set_height(ui_OscilloscopeChart2, 130);
    lv_obj_set_x(ui_OscilloscopeChart2, 0);
    lv_obj_set_y(ui_OscilloscopeChart2, -17);
    lv_obj_set_align(ui_OscilloscopeChart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_OscilloscopeChart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_OscilloscopeChart2, 200);
    lv_chart_set_range(ui_OscilloscopeChart2, LV_CHART_AXIS_PRIMARY_Y, 0, 3300);
    lv_chart_set_axis_tick(ui_OscilloscopeChart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_OscilloscopeChart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_OscilloscopeChart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);



    lv_obj_set_style_line_color(ui_OscilloscopeChart2, lv_color_hex(0x20F080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_OscilloscopeChart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label30, ui_event_Label30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screenshot_screen, ui_event_Screenshot_screen, LV_EVENT_ALL, NULL);

}
