// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Temp_and_humididty_history_screen_screen_init(void)
{
    ui_Temp_and_humididty_history_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Temp_and_humididty_history_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button14 = lv_btn_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Button14, 52);
    lv_obj_set_height(ui_Button14, 25);
    lv_obj_set_x(ui_Button14, -126);
    lv_obj_set_y(ui_Button14, 99);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Button14, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Button14, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Label32 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Back");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature_chart = lv_chart_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Temperature_chart, 200);
    lv_obj_set_height(ui_Temperature_chart, 80);
    lv_obj_set_x(ui_Temperature_chart, 1);
    lv_obj_set_y(ui_Temperature_chart, -63);
    lv_obj_set_align(ui_Temperature_chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Temperature_chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Temperature_chart, 60);
    lv_chart_set_range(ui_Temperature_chart, LV_CHART_AXIS_PRIMARY_Y, 1500, 3100);
    lv_chart_set_axis_tick(ui_Temperature_chart, LV_CHART_AXIS_PRIMARY_X, 5, 5, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_Temperature_chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 3, 2, false, 50);
    lv_chart_set_axis_tick(ui_Temperature_chart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, false, 25);

    lv_obj_set_style_line_color(ui_Temperature_chart, lv_color_hex(0xDC0A0A), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Temperature_chart, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Temperature_chart, lv_color_hex(0x20F080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Temperature_chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Temperature_chart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature_chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -129);
    lv_obj_set_y(ui_Label34, -93);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "30 °C");
    lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -128);
    lv_obj_set_y(ui_Label1, -33);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "15 °C");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -132);
    lv_obj_set_y(ui_Label33, -64);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "22.5 °C");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity_chart = lv_chart_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Humidity_chart, 200);
    lv_obj_set_height(ui_Humidity_chart, 80);
    lv_obj_set_x(ui_Humidity_chart, 0);
    lv_obj_set_y(ui_Humidity_chart, 40);
    lv_obj_set_align(ui_Humidity_chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Humidity_chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Humidity_chart, 60);
    lv_chart_set_axis_tick(ui_Humidity_chart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_Humidity_chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 3, 2, false, 50);
    lv_chart_set_axis_tick(ui_Humidity_chart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, false, 25);

    lv_obj_set_style_line_color(ui_Humidity_chart, lv_color_hex(0x3131FE), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Humidity_chart, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Humidity_chart, lv_color_hex(0x20F080), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Humidity_chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 0);
    lv_obj_set_y(ui_Label35, -111);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Temperature");
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, 88);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Humidity");
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -127);
    lv_obj_set_y(ui_Label37, 39);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "50 %");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -130);
    lv_obj_set_y(ui_Label38, 9);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "100 %");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -124);
    lv_obj_set_y(ui_Label39, 68);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "0 %");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Temp_and_humididty_history_screen);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 119);
    lv_obj_set_y(ui_Label40, -9);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "(minutes)");
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp_and_humididty_history_screen, ui_event_Temp_and_humididty_history_screen, LV_EVENT_ALL,
                        NULL);

}
