// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Final_Project

#include "../ui.h"

void ui_Welcome_screen_screen_init(void)
{
    ui_Welcome_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Welcome_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Welcome_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Welcome_screen, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Welcome_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Welcome_screen, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_Welcome_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_Welcome_screen, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Function_generator_button = lv_btn_create(ui_Welcome_screen);
    lv_obj_set_width(ui_Function_generator_button, 185);
    lv_obj_set_height(ui_Function_generator_button, 40);
    lv_obj_set_x(ui_Function_generator_button, 0);
    lv_obj_set_y(ui_Function_generator_button, -60);
    lv_obj_set_align(ui_Function_generator_button, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Function_generator_button, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_style_bg_color(ui_Function_generator_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Function_generator_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Function_generator_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Function_generator_button, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Function_generator_button, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Function_generator_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Function_generator_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Function_generator_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Function_generator_label = lv_label_create(ui_Function_generator_button);
    lv_obj_set_width(ui_Function_generator_label, 146);
    lv_obj_set_height(ui_Function_generator_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Function_generator_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Function_generator_label, "Function generator");
    lv_obj_set_style_text_color(ui_Function_generator_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Function_generator_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Function_generator_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Osciloscope_button = lv_btn_create(ui_Welcome_screen);
    lv_obj_set_width(ui_Osciloscope_button, 185);
    lv_obj_set_height(ui_Osciloscope_button, 40);
    lv_obj_set_x(ui_Osciloscope_button, 0);
    lv_obj_set_y(ui_Osciloscope_button, -10);
    lv_obj_set_align(ui_Osciloscope_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Osciloscope_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Osciloscope_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Osciloscope_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Osciloscope_button, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_Osciloscope_button, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_Osciloscope_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_Osciloscope_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_Osciloscope_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Oscilocope_label = lv_label_create(ui_Osciloscope_button);
    lv_obj_set_width(ui_Oscilocope_label, 100);
    lv_obj_set_height(ui_Oscilocope_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Oscilocope_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Oscilocope_label, "Oscilloscope");
    lv_obj_set_style_text_color(ui_Oscilocope_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Oscilocope_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Oscilocope_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_More_options_button = lv_btn_create(ui_Welcome_screen);
    lv_obj_set_width(ui_More_options_button, 185);
    lv_obj_set_height(ui_More_options_button, 40);
    lv_obj_set_x(ui_More_options_button, 0);
    lv_obj_set_y(ui_More_options_button, 40);
    lv_obj_set_align(ui_More_options_button, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_More_options_button, lv_color_hex(0x20F080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_More_options_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_More_options_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_More_options_button, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_More_options_button, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_More_options_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_More_options_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(ui_More_options_button, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(ui_More_options_button, 2, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    ui_Split_screen_label = lv_label_create(ui_More_options_button);
    lv_obj_set_width(ui_Split_screen_label, 106);
    lv_obj_set_height(ui_Split_screen_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Split_screen_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Split_screen_label, "More options");
    lv_obj_set_style_text_color(ui_Split_screen_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Split_screen_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Split_screen_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Welcome_screen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -5);
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label3, "ByteLab Embedded software academy 2024.");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel1 = lv_label_create(ui_Welcome_screen);
    lv_obj_set_width(ui_TemperatureLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureLabel1, -80);
    lv_obj_set_y(ui_TemperatureLabel1, -110);
    lv_obj_set_align(ui_TemperatureLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureLabel1, "Temperature: 0 °C");
    lv_obj_set_style_text_font(ui_TemperatureLabel1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel1 = lv_label_create(ui_Welcome_screen);
    lv_obj_set_width(ui_HumidityLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabel1, 70);
    lv_obj_set_y(ui_HumidityLabel1, -110);
    lv_obj_set_align(ui_HumidityLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel1, "Humidity: 0%");
    lv_obj_set_style_text_font(ui_HumidityLabel1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Function_generator_button, ui_event_Function_generator_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Osciloscope_button, ui_event_Osciloscope_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_More_options_button, ui_event_More_options_button, LV_EVENT_ALL, NULL);

}
